{% set name = "python-nomad" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-nomad-{{ version }}.tar.gz
  sha256: 5699e026f9bd78aeb494f78521b8e74f0cd65a827db5104360fe528210cc6c08

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests

test:
  imports:
    - nomad
    - nomad.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/jrxfive/python-nomad
  summary: Client library for Hashicorp Nomad
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
