{% set name = "python-nomad" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-nomad-{{ version }}.tar.gz
  sha256: e48c87370d40ac4f1f53d0e849030690323d77f3a2475608ffb9d33de1482be0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests

test:
  imports:
    - nomad
    - nomad.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/jrxfive/python-nomad
  summary: Client library for Hashicorp Nomad
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
