{% set name = "python-nomad" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4d70a6e85c58a1abe33770128a843bc97415b030d779d0ca0601863fc82141d3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - nomad
    - nomad.api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/jrxfive/python-nomad
  summary: Client library for Hashicorp Nomad
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
